# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d03de51cd5bb68108479ede5df40689b5b9bac23adaf9a811997d324a4b9465cd5e33077d5b610385731f2c4fc731ef1ecfe67a9c7969e22d9f7c9e1322f914

test:
  secret_key_base: e645aeb01f61a6a34b6b9d485c10db8577bada085ba53d6758aaedbd6c6b58a44f5dfa7065532c717afbd9e3692f73e47e9f762c719317a981c8dfa6603ead8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
